export const INCREASE_BEER_NUMBER = "INCREASE_BEER_NUMBER";
export const DECREASE_BEER_NUMBER = "DECREASE_BEER_NUMBER";
export const ADD_NEW_DRINKING_BUDDY = "ADD_NEW_DRINKING_BUDDY";
export const DELETE_DRINKING_BUDDY = "DELETE_DRINKING_BUDDY";
